# pylint: disable=too-many-lines

from pathlib import Path
from typing import Optional, Tuple
import os
from gitential2.datatypes.extraction import Langtype


# pylint: disable=unused-argument
def detect_lang(
    file_path,
    file_size: Optional[int] = 0,
    is_binary: bool = False,
    commit_id: Optional[str] = None,
    repo_path: Optional[Path] = None,
) -> Tuple[str, Langtype]:

    name, ext = os.path.basename(file_path), os.path.splitext(file_path)[1]
    matched_by_name = DEFAULT_FILENAME_INDEX.get(name, None)
    if matched_by_name is not None:
        return (matched_by_name[0][0], Langtype(matched_by_name[0][1]))

    matched_by_ext = DEFAULT_EXTENSION_INDEX.get(ext, None)
    if matched_by_ext is not None:
        return (matched_by_ext[0][0], Langtype(matched_by_ext[0][1]))

    return ("unknown", Langtype.UNKNOWN)


DEFAULT_FILENAME_INDEX = {
    ".Rprofile": (("R", 1),),
    ".XCompose": (("XCompose", 4),),
    ".abbrev_defs": (("Emacs Lisp", 1),),
    ".arcconfig": (("JSON", 4),),
    ".babelrc": (("JSON5", 4),),
    ".bash_history": (("Shell", 1),),
    ".bash_logout": (("Shell", 1),),
    ".bash_profile": (("Shell", 1),),
    ".bashrc": (("Shell", 1),),
    ".clang-format": (("YAML", 4),),
    ".clang-tidy": (("YAML", 4),),
    ".classpath": (("XML", 4),),
    ".cproject": (("XML", 4),),
    ".cshrc": (("Shell", 1),),
    ".editorconfig": (("INI", 4),),
    ".emacs": (("Emacs Lisp", 1),),
    ".emacs.desktop": (("Emacs Lisp", 1),),
    ".factor-boot-rc": (("Factor", 1),),
    ".factor-rc": (("Factor", 1),),
    ".gclient": (("Python", 1),),
    ".gemrc": (("YAML", 4),),
    ".gitconfig": (("INI", 4),),
    ".gn": (("GN", 4),),
    ".gnus": (("Emacs Lisp", 1),),
    ".gvimrc": (("Vim script", 1),),
    ".htaccess": (("ApacheConf", 4),),
    ".htmlhintrc": (("JSON", 4),),
    ".irbrc": (("Ruby", 1),),
    ".jscsrc": (("JSON", 4),),
    ".jshintrc": (("JSON", 4),),
    ".jslintrc": (("JSON5", 4),),
    ".login": (("Shell", 1),),
    ".nvimrc": (("Vim script", 1),),
    ".php": (("PHP", 1),),
    ".php_cs": (("PHP", 1),),
    ".php_cs.dist": (("PHP", 1),),
    ".profile": (("Shell", 1),),
    ".project": (("XML", 4),),
    ".pryrc": (("Ruby", 1),),
    ".spacemacs": (("Emacs Lisp", 1),),
    ".tern-config": (("JSON", 4),),
    ".tern-project": (("JSON", 4),),
    ".vimrc": (("Vim script", 1),),
    ".viper": (("Emacs Lisp", 1),),
    ".zlogin": (("Shell", 1),),
    ".zlogout": (("Shell", 1),),
    ".zprofile": (("Shell", 1),),
    ".zshenv": (("Shell", 1),),
    ".zshrc": (("Shell", 1),),
    "9fs": (("Shell", 1),),
    "APKBUILD": (("Alpine Abuild", 1),),
    "App.config": (("XML", 4),),
    "Appraisals": (("Ruby", 1),),
    "BSDmakefile": (("Makefile", 1),),
    "BUCK": (("Python", 1),),
    "BUILD": (("Python", 1),),
    "BUILD.bazel": (("Python", 1),),
    "Berksfile": (("Ruby", 1),),
    "Brewfile": (("Ruby", 1),),
    "Buildfile": (("Ruby", 1),),
    "CMakeLists.txt": (("CMake", 1),),
    "COPYING": (("Text", 3),),
    "COPYING.regex": (("Text", 3),),
    "COPYRIGHT.regex": (("Text", 3),),
    "Cakefile": (("CoffeeScript", 1),),
    "Capfile": (("Ruby", 1),),
    "Cask": (("Emacs Lisp", 1),),
    "Dangerfile": (("Ruby", 1),),
    "Deliverfile": (("Ruby", 1),),
    "Dockerfile": (("Dockerfile", 4),),
    "Emakefile": (("Erlang", 1),),
    "FONTLOG": (("Text", 3),),
    "Fakefile": (("Fancy", 1),),
    "Fastfile": (("Ruby", 1),),
    "GNUmakefile": (("Makefile", 1),),
    "Gemfile": (("Ruby", 1),),
    "Gemfile.lock": (("Ruby", 1),),
    "Guardfile": (("Ruby", 1),),
    "INSTALL": (("Text", 3),),
    "INSTALL.mysql": (("Text", 3),),
    "Jakefile": (("JavaScript", 1),),
    "Jarfile": (("Ruby", 1),),
    "Jenkinsfile": (("Groovy", 1),),
    "Kbuild": (("Makefile", 1),),
    "LICENSE": (("Text", 3),),
    "LICENSE.mysql": (("Text", 3),),
    "Makefile": (("Makefile", 1),),
    "Makefile.am": (("Makefile", 1),),
    "Makefile.boot": (("Makefile", 1),),
    "Makefile.frag": (("Makefile", 1),),
    "Makefile.in": (("Makefile", 1),),
    "Makefile.inc": (("Makefile", 1),),
    "Makefile.wat": (("Makefile", 1),),
    "Mavenfile": (("Ruby", 1),),
    "Modulefile": (("Puppet", 1),),
    "NEWS": (("Text", 3),),
    "Notebook": (("Jupyter Notebook", 2),),
    "NuGet.config": (("XML", 4),),
    "Nukefile": (("Nu", 1),),
    "PKGBUILD": (("Shell", 1),),
    "Phakefile": (("PHP", 1),),
    "Podfile": (("Ruby", 1),),
    "Project.ede": (("Emacs Lisp", 1),),
    "Puppetfile": (("Ruby", 1),),
    "README.1ST": (("Text", 3),),
    "README.me": (("Text", 3),),
    "README.mysql": (("Text", 3),),
    "ROOT": (("Isabelle ROOT", 1),),
    "Rakefile": (("Ruby", 1),),
    "Rexfile": (("Perl 6", 1),),
    "SConscript": (("Python", 1),),
    "SConstruct": (("Python", 1),),
    "Settings.StyleCop": (("XML", 4),),
    "Slakefile": (("LiveScript", 1),),
    "Snakefile": (("Python", 1),),
    "Snapfile": (("Ruby", 1),),
    "Thorfile": (("Ruby", 1),),
    "Vagrantfile": (("Ruby", 1),),
    "WORKSPACE": (("Python", 1),),
    "Web.Debug.config": (("XML", 4),),
    "Web.Release.config": (("XML", 4),),
    "Web.config": (("XML", 4),),
    "XCompose": (("XCompose", 4),),
    "_emacs": (("Emacs Lisp", 1),),
    "_vimrc": (("Vim script", 1),),
    "abbrev_defs": (("Emacs Lisp", 1),),
    "ack": (("Perl", 1),),
    "ant.xml": (("Ant Build System", 4),),
    "apache2.conf": (("ApacheConf", 4),),
    "bash_logout": (("Shell", 1),),
    "bash_profile": (("Shell", 1),),
    "bashrc": (("Shell", 1),),
    "build.xml": (("Ant Build System", 4),),
    "buildfile": (("Ruby", 1),),
    "buildozer.spec": (("INI", 4),),
    "click.me": (("Text", 3),),
    "composer.lock": (("JSON", 4),),
    "configure.ac": (("M4Sugar", 1),),
    "cpanfile": (("Perl", 1),),
    "cshrc": (("Shell", 1),),
    "delete.me": (("Text", 3),),
    "descrip.mmk": (("Module Management System", 1),),
    "descrip.mms": (("Module Management System", 1),),
    "expr-dist": (("R", 1),),
    "fp-lib-table": (("KiCad Layout", 4),),
    "gradlew": (("Shell", 1),),
    "gvimrc": (("Vim script", 1),),
    "httpd.conf": (("ApacheConf", 4),),
    "keep.me": (("Text", 3),),
    "ld.script": (("Linker Script", 4),),
    "login": (("Shell", 1),),
    "makefile": (("Makefile", 1),),
    "makefile.sco": (("Makefile", 1),),
    "man": (("Shell", 1),),
    "mcmod.info": (("JSON", 4),),
    "meson.build": (("Meson", 1),),
    "meson_options.txt": (("Meson", 1),),
    "mix.lock": (("Elixir", 1),),
    "mkfile": (("Makefile", 1),),
    "mmn": (("Roff", 2),),
    "mmt": (("Roff", 2),),
    "nextflow.config": (("Nextflow", 1),),
    "nginx.conf": (("Nginx", 4),),
    "nvimrc": (("Vim script", 1),),
    "owh": (("Tcl", 1),),
    "packages.config": (("XML", 4),),
    "pom.xml": (("Maven POM", 4),),
    "profile": (("Shell", 1),),
    "read.me": (("Text", 3),),
    "readme.1st": (("Text", 3),),
    "rebar.config": (("Erlang", 1),),
    "rebar.config.lock": (("Erlang", 1),),
    "rebar.lock": (("Erlang", 1),),
    "riemann.config": (("Clojure", 1),),
    "script": (("C", 1),),
    "starfield": (("Tcl", 1),),
    "test.me": (("Text", 3),),
    "vimrc": (("Vim script", 1),),
    "wscript": (("Python", 1),),
    "xcompose": (("XCompose", 4),),
    "zlogin": (("Shell", 1),),
    "zlogout": (("Shell", 1),),
    "zprofile": (("Shell", 1),),
    "zshenv": (("Shell", 1),),
    "zshrc": (("Shell", 1),),
}

DEFAULT_EXTENSION_INDEX = {
    ".1": (("Roff", 2),),
    ".1in": (("Roff", 2),),
    ".1m": (("Roff", 2),),
    ".1x": (("Roff", 2),),
    ".2": (("Roff", 2),),
    ".3": (("Roff", 2),),
    ".3in": (("Roff", 2),),
    ".3m": (("Roff", 2),),
    ".3qt": (("Roff", 2),),
    ".3x": (("Roff", 2),),
    ".4": (("Roff", 2),),
    ".4TH": (("Forth", 1),),
    ".4th": (("Forth", 1),),
    ".5": (("Roff", 2),),
    ".6": (("Roff", 2),),
    ".6pl": (("Perl 6", 1),),
    ".6pm": (("Perl 6", 1),),
    ".7": (("Roff", 2),),
    ".8": (("Roff", 2),),
    ".8xk": (("TI Program", 1),),
    ".8xk.txt": (("TI Program", 1),),
    ".8xp": (("TI Program", 1),),
    ".8xp.txt": (("TI Program", 1),),
    ".9": (("Roff", 2),),
    ".C": (("C", 1),),
    ".DOT": (("Graphviz (DOT)", 4),),
    ".E": (("E", 1),),
    ".F": (("Fortran", 1), ("Forth", 1)),
    ".H": (("C", 1),),
    ".JSON-tmLanguage": (("JSON", 4),),
    ".ML": (("Standard ML", 1),),
    ".R": (("R", 1),),
    ".RNH": (("RUNOFF", 2),),
    ".Rd": (("R", 1),),
    ".YAML-tmLanguage": (("YAML", 4),),
    "._coffee": (("CoffeeScript", 1),),
    "._js": (("JavaScript", 1),),
    "._ls": (("LiveScript", 1),),
    ".a51": (("Assembly", 1),),
    ".abap": (("ABAP", 1),),
    ".abnf": (("ABNF", 4),),
    ".ada": (("Ada", 1),),
    ".adb": (("Ada", 1),),
    ".adml": (("XML", 4),),
    ".admx": (("XML", 4),),
    ".ado": (("Stata", 1),),
    ".adoc": (("AsciiDoc", 3),),
    ".adp": (("Tcl", 1),),
    ".ads": (("Ada", 1),),
    ".afm": (("Adobe Font Metrics", 4),),
    ".agc": (("Apollo Guidance Computer", 1),),
    ".agda": (("Agda", 1),),
    ".ahk": (("AutoHotkey", 1),),
    ".ahkl": (("AutoHotkey", 1),),
    ".aj": (("AspectJ", 1),),
    ".al": (("Perl", 1),),
    ".als": (("Alloy", 1),),
    ".ampl": (("AMPL", 1),),
    ".angelscript": (("AngelScript", 1),),
    ".anim": (("Unity3D Asset", 4),),
    ".ant": (("XML", 4),),
    ".apacheconf": (("ApacheConf", 4),),
    ".apib": (("API Blueprint", 2),),
    ".apl": (("APL", 1),),
    ".app.src": (("Erlang", 1),),
    ".applescript": (("AppleScript", 1),),
    ".arc": (("Arc", 1),),
    ".arpa": (("DNS Zone", 4),),
    ".as": (("ActionScript", 1), ("AngelScript", 1)),
    ".asax": (("ASP", 1),),
    ".asc": (("Public Key", 4), ("AsciiDoc", 3), ("AGS Script", 1)),
    ".asciidoc": (("AsciiDoc", 3),),
    ".ascx": (("ASP", 1),),
    ".asd": (("Common Lisp", 1),),
    ".ash": (("AGS Script", 1),),
    ".ashx": (("ASP", 1),),
    ".asm": (("Assembly", 1),),
    ".asmx": (("ASP", 1),),
    ".asn": (("ASN.1", 4),),
    ".asn1": (("ASN.1", 4),),
    ".asp": (("ASP", 1),),
    ".aspx": (("ASP", 1),),
    ".asset": (("Unity3D Asset", 4),),
    ".au3": (("AutoIt", 1),),
    ".aug": (("Augeas", 1),),
    ".auk": (("Awk", 1),),
    ".aux": (("TeX", 2),),
    ".avsc": (("JSON", 4),),
    ".aw": (("PHP", 1),),
    ".awk": (("Awk", 1),),
    ".axd": (("ASP", 1),),
    ".axi": (("NetLinx", 1),),
    ".axi.erb": (("NetLinx+ERB", 1),),
    ".axml": (("XML", 4),),
    ".axs": (("NetLinx", 1),),
    ".axs.erb": (("NetLinx+ERB", 1),),
    ".b": (("Brainfuck", 1), ("Limbo", 1)),
    ".backup": (("JSON", 4),),
    ".bal": (("Ballerina", 1),),
    ".bas": (("Visual Basic", 1),),
    ".bash": (("Shell", 1),),
    ".bat": (("Batchfile", 1),),
    ".bats": (("Shell", 1),),
    ".bb": (("BitBake", 1), ("BlitzBasic", 1)),
    ".bbx": (("TeX", 2),),
    ".bdy": (("PLSQL", 1),),
    ".befunge": (("Befunge", 1),),
    ".bf": (("Brainfuck", 1), ("HyPhy", 1)),
    ".bib": (("TeX", 2),),
    ".bison": (("Bison", 1),),
    ".blade": (("Blade", 2),),
    ".blade.php": (("Blade", 2),),
    ".bmx": (("BlitzMax", 1),),
    ".bones": (("JavaScript", 1),),
    ".boo": (("Boo", 1),),
    ".boot": (("Clojure", 1),),
    ".brd": (("Eagle", 4), ("KiCad Legacy Layout", 4)),
    ".bro": (("Bro", 1),),
    ".brs": (("Brightscript", 1),),
    ".bsl": (("1C Enterprise", 1),),
    ".bsv": (("Bluespec", 1),),
    ".builder": (("Ruby", 1),),
    ".builds": (("XML", 4),),
    ".bzl": (("Python", 1),),
    ".c": (("C", 1),),
    ".c++": (("C++", 1),),
    ".c++-objdump": (("Cpp-ObjDump", 4),),
    ".c++objdump": (("Cpp-ObjDump", 4),),
    ".c-objdump": (("C-ObjDump", 4),),
    ".cake": (("C#", 1), ("CoffeeScript", 1)),
    ".capnp": (("Cap'n Proto", 1),),
    ".cats": (("C", 1),),
    ".cbl": (("COBOL", 1),),
    ".cbx": (("TeX", 2),),
    ".cc": (("C++", 1),),
    ".ccp": (("COBOL", 1),),
    ".ccproj": (("XML", 4),),
    ".ccxml": (("XML", 4),),
    ".cdf": (("Mathematica", 1),),
    ".ceylon": (("Ceylon", 1),),
    ".cfc": (("ColdFusion CFC", 1),),
    ".cfg": (("INI", 4),),
    ".cfm": (("ColdFusion", 1),),
    ".cfml": (("ColdFusion", 1),),
    ".cgi": (("Perl", 1), ("Python", 1), ("Shell", 1)),
    ".cginc": (("HLSL", 1),),
    ".ch": (("Charity", 1), ("xBase", 1)),
    ".chem": (("Pic", 2),),
    ".chpl": (("Chapel", 1),),
    ".chs": (("C2hs Haskell", 1),),
    ".cirru": (("Cirru", 1),),
    ".cjsx": (("CoffeeScript", 1),),
    ".ck": (("ChucK", 1),),
    ".cl": (("Common Lisp", 1), ("Cool", 1), ("OpenCL", 1)),
    ".cl2": (("Clojure", 1),),
    ".click": (("Click", 1),),
    ".clixml": (("XML", 4),),
    ".clj": (("Clojure", 1),),
    ".cljc": (("Clojure", 1),),
    ".cljs": (("Clojure", 1),),
    ".cljs.hl": (("Clojure", 1),),
    ".cljscm": (("Clojure", 1),),
    ".cljx": (("Clojure", 1),),
    ".clp": (("CLIPS", 1),),
    ".cls": (("TeX", 2), ("Apex", 1), ("OpenEdge ABL", 1), ("Visual Basic", 1)),
    ".clw": (("Clarion", 1),),
    ".cmake": (("CMake", 1),),
    ".cmake.in": (("CMake", 1),),
    ".cmd": (("Batchfile", 1),),
    ".cob": (("COBOL", 1),),
    ".cobol": (("COBOL", 1),),
    ".coffee": (("CoffeeScript", 1),),
    ".com": (("DIGITAL Command Language", 1),),
    ".command": (("Shell", 1),),
    ".config": (("XML", 4),),
    ".conll": (("CoNLL-U", 4),),
    ".conllu": (("CoNLL-U", 4),),
    ".coq": (("Coq", 1),),
    ".cp": (("C++", 1), ("Component Pascal", 1)),
    ".cpp": (("C++", 1),),
    ".cpp-objdump": (("Cpp-ObjDump", 4),),
    ".cppobjdump": (("Cpp-ObjDump", 4),),
    ".cproject": (("XML", 4),),
    ".cps": (("Component Pascal", 1),),
    ".cpy": (("COBOL", 1),),
    ".cql": (("SQL", 4),),
    ".cr": (("Crystal", 1),),
    ".creole": (("Creole", 3),),
    ".cs": (("C#", 1), ("Smalltalk", 1)),
    ".cscfg": (("XML", 4),),
    ".csd": (("Csound Document", 1),),
    ".csdef": (("XML", 4),),
    ".csh": (("Tcsh", 1),),
    ".cshtml": (("C#", 1),),
    ".csl": (("XML", 4),),
    ".cson": (("CSON", 4),),
    ".csproj": (("XML", 4),),
    ".css": (("CSS", 2),),
    ".csv": (("CSV", 4),),
    ".csx": (("C#", 1),),
    ".ct": (("XML", 4),),
    ".ctp": (("PHP", 1),),
    ".cu": (("Cuda", 1),),
    ".cuh": (("Cuda", 1),),
    ".cw": (("Redcode", 1),),
    ".cwl": (("Common Workflow Language", 1),),
    ".cxx": (("C++", 1),),
    ".cxx-objdump": (("Cpp-ObjDump", 4),),
    ".cy": (("Cycript", 1),),
    ".d": (("D", 1), ("DTrace", 1), ("Makefile", 1)),
    ".d-objdump": (("D-ObjDump", 4),),
    ".dae": (("COLLADA", 4),),
    ".darcspatch": (("Darcs Patch", 4),),
    ".dart": (("Dart", 1),),
    ".dats": (("ATS", 1),),
    ".db2": (("SQLPL", 1),),
    ".dcl": (("Clean", 1),),
    ".ddl": (("SQL", 4), ("PLSQL", 1)),
    ".decls": (("BlitzBasic", 1),),
    ".deface": (("HTML+ERB", 2), ("Haml", 2)),
    ".depproj": (("XML", 4),),
    ".desktop": (("desktop", 4), ("Emacs Lisp", 1)),
    ".desktop.in": (("desktop", 4),),
    ".dfm": (("Pascal", 1),),
    ".di": (("D", 1),),
    ".diff": (("Diff", 4),),
    ".dist": (("XML", 4),),
    ".dita": (("XML", 4),),
    ".ditamap": (("XML", 4),),
    ".ditaval": (("XML", 4),),
    ".djs": (("Dogescript", 1),),
    ".dll.config": (("XML", 4),),
    ".dlm": (("IDL", 1),),
    ".dm": (("DM", 1),),
    ".do": (("Stata", 1),),
    ".dockerfile": (("Dockerfile", 4),),
    ".doh": (("Stata", 1),),
    ".dot": (("Graphviz (DOT)", 4),),
    ".dotsettings": (("XML", 4),),
    ".dpatch": (("Darcs Patch", 4),),
    ".dpr": (("Pascal", 1),),
    ".druby": (("Mirah", 1),),
    ".dtx": (("TeX", 2),),
    ".duby": (("Mirah", 1),),
    ".dwl": (("DataWeave", 1),),
    ".dyalog": (("APL", 1),),
    ".dyl": (("Dylan", 1),),
    ".dylan": (("Dylan", 1),),
    ".e": (("Eiffel", 1),),
    ".eam.fs": (("Formatted", 4),),
    ".eb": (("Easybuild", 4),),
    ".ebnf": (("EBNF", 4),),
    ".ebuild": (("Gentoo Ebuild", 1),),
    ".ec": (("eC", 1),),
    ".ecl": (("ECL", 1), ("ECLiPSe", 1)),
    ".eclass": (("Gentoo Eclass", 1),),
    ".eclxml": (("ECL", 1),),
    ".ecr": (("HTML+ECR", 2),),
    ".edc": (("Edje Data Collection", 4),),
    ".edn": (("edn", 4),),
    ".eex": (("HTML+EEX", 2),),
    ".eh": (("eC", 1),),
    ".ejs": (("EJS", 2),),
    ".el": (("Emacs Lisp", 1),),
    ".eliom": (("OCaml", 1),),
    ".eliomi": (("OCaml", 1),),
    ".elm": (("Elm", 1),),
    ".em": (("EmberScript", 1),),
    ".emacs": (("Emacs Lisp", 1),),
    ".emacs.desktop": (("Emacs Lisp", 1),),
    ".emberscript": (("EmberScript", 1),),
    ".epj": (("Ecere Projects", 4),),
    ".eps": (("PostScript", 2),),
    ".eq": (("EQ", 1),),
    ".erb": (("HTML+ERB", 2), ("NetLinx+ERB", 1)),
    ".erb.deface": (("HTML+ERB", 2),),
    ".erl": (("Erlang", 1),),
    ".es": (("JavaScript", 1), ("Erlang", 1)),
    ".es6": (("JavaScript", 1),),
    ".escript": (("Erlang", 1),),
    ".ex": (("Elixir", 1),),
    ".exs": (("Elixir", 1),),
    ".eye": (("Ruby", 1),),
    ".f": (("Fortran", 1), ("Filebench WML", 1), ("Forth", 1)),
    ".f03": (("Fortran", 1),),
    ".f08": (("Fortran", 1),),
    ".f77": (("Fortran", 1),),
    ".f90": (("Fortran", 1),),
    ".f95": (("Fortran", 1),),
    ".factor": (("Factor", 1),),
    ".fan": (("Fantom", 1),),
    ".fancypack": (("Fancy", 1),),
    ".fcgi": (("Lua", 1), ("PHP", 1), ("Perl", 1), ("Python", 1), ("Ruby", 1), ("Shell", 1)),
    ".fea": (("OpenType Feature File", 4),),
    ".feature": (("Gherkin", 1),),
    ".filters": (("XML", 4),),
    ".fish": (("fish", 1),),
    ".flex": (("JFlex", 1),),
    ".flux": (("FLUX", 1),),
    ".fnc": (("PLSQL", 1),),
    ".for": (("Fortran", 1), ("Formatted", 4), ("Forth", 1)),
    ".forth": (("Forth", 1),),
    ".fp": (("GLSL", 1),),
    ".fpp": (("Fortran", 1),),
    ".fr": (("Text", 3), ("Forth", 1), ("Frege", 1)),
    ".frag": (("GLSL", 1), ("JavaScript", 1)),
    ".frg": (("GLSL", 1),),
    ".frm": (("Visual Basic", 1),),
    ".frt": (("Forth", 1),),
    ".frx": (("Visual Basic", 1),),
    ".fs": (("F#", 1), ("Formatted", 4), ("Filterscript", 1), ("Forth", 1), ("GLSL", 1)),
    ".fsh": (("GLSL", 1),),
    ".fshader": (("GLSL", 1),),
    ".fsi": (("F#", 1),),
    ".fsproj": (("XML", 4),),
    ".fsx": (("F#", 1),),
    ".fth": (("Forth", 1),),
    ".ftl": (("FreeMarker", 1),),
    ".fun": (("Standard ML", 1),),
    ".fx": (("FLUX", 1), ("HLSL", 1)),
    ".fxh": (("HLSL", 1),),
    ".fxml": (("XML", 4),),
    ".fy": (("Fancy", 1),),
    ".g": (("G-code", 4), ("GAP", 1)),
    ".g4": (("ANTLR", 1),),
    ".gap": (("GAP", 1),),
    ".gawk": (("Awk", 1),),
    ".gbl": (("Gerber Image", 4),),
    ".gbo": (("Gerber Image", 4),),
    ".gbp": (("Gerber Image", 4),),
    ".gbr": (("Gerber Image", 4),),
    ".gbs": (("Gerber Image", 4),),
    ".gco": (("G-code", 4),),
    ".gcode": (("G-code", 4),),
    ".gd": (("GAP", 1), ("GDScript", 1)),
    ".gdb": (("GDB", 1),),
    ".gdbinit": (("GDB", 1),),
    ".gemspec": (("Ruby", 1),),
    ".geo": (("GLSL", 1),),
    ".geojson": (("JSON", 4),),
    ".geom": (("GLSL", 1),),
    ".gf": (("Grammatical Framework", 1),),
    ".gi": (("GAP", 1),),
    ".gko": (("Gerber Image", 4),),
    ".glade": (("XML", 4),),
    ".glf": (("Glyph", 1),),
    ".glsl": (("GLSL", 1),),
    ".glslv": (("GLSL", 1),),
    ".gltf": (("JSON", 4),),
    ".gml": (("Graph Modeling Language", 4), ("XML", 4), ("Game Maker Language", 1)),
    ".gms": (("GAMS", 1),),
    ".gn": (("GN", 4),),
    ".gni": (("GN", 4),),
    ".gnu": (("Gnuplot", 1),),
    ".gnuplot": (("Gnuplot", 1),),
    ".go": (("Go", 1),),
    ".god": (("Ruby", 1),),
    ".golo": (("Golo", 1),),
    ".gp": (("Gnuplot", 1),),
    ".gpb": (("Gerber Image", 4),),
    ".gpt": (("Gerber Image", 4),),
    ".gql": (("GraphQL", 4),),
    ".grace": (("Grace", 1),),
    ".gradle": (("Gradle", 4),),
    ".graphql": (("GraphQL", 4),),
    ".groovy": (("Groovy", 1),),
    ".grt": (("Groovy", 1),),
    ".grxml": (("XML", 4),),
    ".gs": (("JavaScript", 1), ("Gosu", 1), ("Genie", 1)),
    ".gshader": (("GLSL", 1),),
    ".gsp": (("Groovy Server Pages", 1),),
    ".gst": (("Gosu", 1),),
    ".gsx": (("Gosu", 1),),
    ".gtl": (("Gerber Image", 4),),
    ".gto": (("Gerber Image", 4),),
    ".gtp": (("Gerber Image", 4),),
    ".gtpl": (("Groovy", 1),),
    ".gts": (("Gerber Image", 4),),
    ".gv": (("Graphviz (DOT)", 4),),
    ".gvy": (("Groovy", 1),),
    ".gyp": (("Python", 1),),
    ".gypi": (("Python", 1),),
    ".h": (("C", 1), ("C++", 1), ("Objective-C", 1)),
    ".h++": (("C++", 1),),
    ".haml": (("Haml", 2),),
    ".haml.deface": (("Haml", 2),),
    ".handlebars": (("Handlebars", 2),),
    ".hats": (("ATS", 1),),
    ".hb": (("Harbour", 1),),
    ".hbs": (("Handlebars", 2),),
    ".hcl": (("HCL", 1),),
    ".hh": (("C++", 1), ("Hack", 1)),
    ".hic": (("Clojure", 1),),
    ".hl": (("Clojure", 1), ("HTML", 2)),
    ".hlean": (("Lean", 1),),
    ".hlsl": (("HLSL", 1),),
    ".hlsli": (("HLSL", 1),),
    ".hpp": (("C++", 1),),
    ".hqf": (("SQF", 1),),
    ".hrl": (("Erlang", 1),),
    ".hs": (("Haskell", 1),),
    ".hsc": (("Haskell", 1),),
    ".htm": (("HTML", 2),),
    ".html": (("HTML", 2),),
    ".html.hl": (("HTML", 2),),
    ".http": (("HTTP", 4),),
    ".hx": (("Haxe", 1),),
    ".hxsl": (("Haxe", 1),),
    ".hxx": (("C++", 1),),
    ".hy": (("Hy", 1),),
    ".i7x": (("Inform 7", 1),),
    ".iced": (("CoffeeScript", 1),),
    ".icl": (("Clean", 1),),
    ".idc": (("C", 1),),
    ".idr": (("Idris", 1),),
    ".ihlp": (("Stata", 1),),
    ".ijs": (("J", 1),),
    ".ik": (("Ioke", 1),),
    ".ily": (("LilyPond", 1),),
    ".iml": (("XML", 4),),
    ".in": (("CMake", 1),),
    ".inc": (
        ("C++", 1),
        ("HTML", 2),
        ("PHP", 1),
        ("SQL", 4),
        ("Assembly", 1),
        ("PAWN", 1),
        ("POV-Ray SDL", 1),
        ("Pascal", 1),
        ("SourcePawn", 1),
    ),
    ".ini": (("INI", 4),),
    ".inl": (("C++", 1),),
    ".ino": (("C++", 1),),
    ".ins": (("TeX", 2),),
    ".intr": (("Dylan", 1),),
    ".io": (("Io", 1),),
    ".iol": (("Jolie", 1),),
    ".ipf": (("IGOR Pro", 1),),
    ".ipp": (("C++", 1),),
    ".ipynb": (("Jupyter Notebook", 2),),
    ".irclog": (("IRC log", 4),),
    ".iss": (("Inno Setup", 1),),
    ".ivy": (("XML", 4),),
    ".j": (("Jasmin", 1), ("Objective-J", 1)),
    ".jade": (("Pug", 2),),
    ".jake": (("JavaScript", 1),),
    ".java": (("Java", 1),),
    ".jbuilder": (("Ruby", 1),),
    ".jelly": (("XML", 4),),
    ".jflex": (("JFlex", 1),),
    ".jinja": (("HTML+Django", 2),),
    ".jison": (("Jison", 1),),
    ".jisonlex": (("Jison Lex", 1),),
    ".jl": (("Julia", 1),),
    ".jq": (("JSONiq", 1),),
    ".js": (("JavaScript", 1),),
    ".jsb": (("JavaScript", 1),),
    ".jscad": (("JavaScript", 1),),
    ".jsfl": (("JavaScript", 1),),
    ".jsm": (("JavaScript", 1),),
    ".json": (("JSON", 4),),
    ".json5": (("JSON5", 4),),
    ".jsonl": (("JSON", 4),),
    ".jsonld": (("JSONLD", 4),),
    ".jsp": (("Java Server Pages", 1),),
    ".jsproj": (("XML", 4),),
    ".jss": (("JavaScript", 1),),
    ".jsx": (("JSX", 1),),
    ".kicad_mod": (("KiCad Layout", 4),),
    ".kicad_pcb": (("KiCad Layout", 4),),
    ".kicad_wks": (("KiCad Layout", 4),),
    ".kid": (("Genshi", 1),),
    ".kit": (("Kit", 2),),
    ".kml": (("XML", 4),),
    ".kojo": (("Scala", 1),),
    ".krl": (("KRL", 1),),
    ".ksh": (("Shell", 1),),
    ".kt": (("Kotlin", 1),),
    ".ktm": (("Kotlin", 1),),
    ".kts": (("Kotlin", 1),),
    ".l": (("Roff", 2), ("Common Lisp", 1), ("Lex", 1), ("PicoLisp", 1)),
    ".lagda": (("Literate Agda", 1),),
    ".las": (("Lasso", 1),),
    ".lasso": (("Lasso", 1),),
    ".lasso8": (("Lasso", 1),),
    ".lasso9": (("Lasso", 1),),
    ".latte": (("Latte", 2),),
    ".launch": (("XML", 4),),
    ".lbx": (("TeX", 2),),
    ".ld": (("Linker Script", 4),),
    ".ldml": (("Lasso", 1),),
    ".lds": (("Linker Script", 4),),
    ".lean": (("Lean", 1),),
    ".less": (("Less", 2),),
    ".lex": (("Lex", 1),),
    ".lfe": (("LFE", 1),),
    ".lgt": (("Logtalk", 1),),
    ".lhs": (("Literate Haskell", 1),),
    ".lid": (("Dylan", 1),),
    ".lidr": (("Idris", 1),),
    ".liquid": (("Liquid", 2),),
    ".lisp": (("Common Lisp", 1), ("NewLisp", 1)),
    ".litcoffee": (("Literate CoffeeScript", 1),),
    ".lkml": (("LookML", 1),),
    ".ll": (("LLVM", 1),),
    ".lmi": (("Python", 1),),
    ".logtalk": (("Logtalk", 1),),
    ".lol": (("LOLCODE", 1),),
    ".lookml": (("LookML", 1),),
    ".lpr": (("Pascal", 1),),
    ".ls": (("LiveScript", 1), ("LoomScript", 1)),
    ".lsl": (("LSL", 1),),
    ".lslp": (("LSL", 1),),
    ".lsp": (("Common Lisp", 1), ("NewLisp", 1)),
    ".ltx": (("TeX", 2),),
    ".lua": (("Lua", 1),),
    ".lvproj": (("LabVIEW", 1),),
    ".ly": (("LilyPond", 1),),
    ".m": (("Matlab", 1), ("Objective-C", 1), ("Limbo", 1), ("M", 1), ("MUF", 1), ("Mathematica", 1), ("Mercury", 1)),
    ".m4": (("M4", 1), ("M4Sugar", 1)),
    ".ma": (("Mathematica", 1),),
    ".mak": (("Makefile", 1),),
    ".make": (("Makefile", 1),),
    ".mako": (("Mako", 1),),
    ".man": (("Roff", 2),),
    ".mao": (("Mako", 1),),
    ".markdown": (("Markdown", 3),),
    ".marko": (("Marko", 2),),
    ".mask": (("Mask", 2),),
    ".mat": (("Unity3D Asset", 4),),
    ".mata": (("Stata", 1),),
    ".matah": (("Stata", 1),),
    ".mathematica": (("Mathematica", 1),),
    ".matlab": (("Matlab", 1),),
    ".mawk": (("Awk", 1),),
    ".maxhelp": (("Max", 1),),
    ".maxpat": (("Max", 1),),
    ".maxproj": (("Max", 1),),
    ".mcr": (("MAXScript", 1),),
    ".md": (("Markdown", 3), ("GCC Machine Description", 1)),
    ".mdown": (("Markdown", 3),),
    ".mdpolicy": (("XML", 4),),
    ".mdwn": (("Markdown", 3),),
    ".me": (("Roff", 2),),
    ".mediawiki": (("MediaWiki", 3),),
    ".meta": (("Unity3D Asset", 4),),
    ".metadata": (("XPages", 4),),
    ".metal": (("Metal", 1),),
    ".minid": (("MiniD", 1),),
    ".mir": (("Mirah", 1),),
    ".mirah": (("Mirah", 1),),
    ".mjml": (("XML", 4),),
    ".mjs": (("JavaScript", 1),),
    ".mk": (("Makefile", 1),),
    ".mkd": (("Markdown", 3),),
    ".mkdn": (("Markdown", 3),),
    ".mkdown": (("Markdown", 3),),
    ".mkfile": (("Makefile", 1),),
    ".mkii": (("TeX", 2),),
    ".mkiv": (("TeX", 2),),
    ".mkvi": (("TeX", 2),),
    ".ml": (("OCaml", 1),),
    ".ml4": (("OCaml", 1),),
    ".mli": (("OCaml", 1),),
    ".mll": (("OCaml", 1),),
    ".mly": (("OCaml", 1),),
    ".mm": (("XML", 4), ("Objective-C++", 1)),
    ".mmk": (("Module Management System", 1),),
    ".mms": (("Module Management System", 1),),
    ".mo": (("Modelica", 1),),
    ".mod": (("Linux Kernel Module", 4), ("XML", 4), ("AMPL", 1), ("Modula-2", 1)),
    ".model.lkml": (("LookML", 1),),
    ".monkey": (("Monkey", 1),),
    ".monkey2": (("Monkey", 1),),
    ".moo": (("Mercury", 1), ("Moocode", 1)),
    ".moon": (("MoonScript", 1),),
    ".mq4": (("MQL4", 1),),
    ".mq5": (("MQL5", 1),),
    ".mqh": (("MQL4", 1), ("MQL5", 1)),
    ".ms": (("MAXScript", 1), ("Unix Assembly", 1), ("Roff", 2)),
    ".mspec": (("Ruby", 1),),
    ".mss": (("CartoCSS", 1),),
    ".mt": (("Mathematica", 1),),
    ".mtl": (("Wavefront Material", 4),),
    ".mtml": (("MTML", 2),),
    ".mu": (("mupad", 1),),
    ".muf": (("MUF", 1),),
    ".mumps": (("M", 1),),
    ".mustache": (("HTML+Django", 2),),
    ".mxml": (("XML", 4),),
    ".mxt": (("Max", 1),),
    ".mysql": (("SQL", 4), ("YAML", 4)),
    ".myt": (("Myghty", 1),),
    ".n": (("Roff", 2), ("Nemerle", 1)),
    ".nasm": (("Assembly", 1),),
    ".natvis": (("XML", 4),),
    ".nawk": (("Awk", 1),),
    ".nb": (("Text", 3), ("Mathematica", 1)),
    ".nbp": (("Mathematica", 1),),
    ".nc": (("nesC", 1),),
    ".ncl": (("Text", 3), ("NCL", 1)),
    ".ndproj": (("XML", 4),),
    ".ne": (("Nearley", 1),),
    ".nearley": (("Nearley", 1),),
    ".nf": (("Nextflow", 1),),
    ".nginxconf": (("Nginx", 4),),
    ".ni": (("Inform 7", 1),),
    ".nim": (("Nim", 1),),
    ".nimrod": (("Nim", 1),),
    ".ninja": (("Ninja", 4),),
    ".nit": (("Nit", 1),),
    ".nix": (("Nix", 1),),
    ".njk": (("HTML+Django", 2),),
    ".njs": (("JavaScript", 1),),
    ".nl": (("NL", 4), ("NewLisp", 1)),
    ".nlogo": (("NetLogo", 1),),
    ".no": (("Text", 3),),
    ".nproj": (("XML", 4),),
    ".nqp": (("Perl 6", 1),),
    ".nr": (("Roff", 2),),
    ".nse": (("Lua", 1),),
    ".nsh": (("NSIS", 1),),
    ".nsi": (("NSIS", 1),),
    ".nu": (("Nu", 1),),
    ".numpy": (("NumPy", 1),),
    ".numpyw": (("NumPy", 1),),
    ".numsc": (("NumPy", 1),),
    ".nuspec": (("XML", 4),),
    ".nut": (("Squirrel", 1),),
    ".ny": (("Common Lisp", 1),),
    ".obj": (("Wavefront Object", 4),),
    ".objdump": (("ObjDump", 4),),
    ".odd": (("XML", 4),),
    ".ol": (("Jolie", 1),),
    ".omgrofl": (("Omgrofl", 1),),
    ".ooc": (("ooc", 1),),
    ".opa": (("Opa", 1),),
    ".opal": (("Opal", 1),),
    ".opencl": (("OpenCL", 1),),
    ".orc": (("Csound", 1),),
    ".org": (("Org", 3),),
    ".os": (("1C Enterprise", 1),),
    ".osm": (("XML", 4),),
    ".owl": (("Web Ontology Language", 4),),
    ".ox": (("Ox", 1),),
    ".oxh": (("Ox", 1),),
    ".oxo": (("Ox", 1),),
    ".oxygene": (("Oxygene", 1),),
    ".oz": (("Oz", 1),),
    ".p": (("OpenEdge ABL", 1),),
    ".p4": (("P4", 1),),
    ".p6": (("Perl 6", 1),),
    ".p6l": (("Perl 6", 1),),
    ".p6m": (("Perl 6", 1),),
    ".pac": (("JavaScript", 1),),
    ".pan": (("Pan", 1),),
    ".parrot": (("Parrot", 1),),
    ".pas": (("Pascal", 1),),
    ".pascal": (("Pascal", 1),),
    ".pasm": (("Parrot Assembly", 1),),
    ".pat": (("Max", 1),),
    ".patch": (("Diff", 4),),
    ".pb": (("PureBasic", 1),),
    ".pbi": (("PureBasic", 1),),
    ".pbt": (("PowerBuilder", 1),),
    ".pck": (("PLSQL", 1),),
    ".pcss": (("PostCSS", 2),),
    ".pd": (("Pure Data", 4),),
    ".pd_lua": (("Lua", 1),),
    ".pde": (("Processing", 1),),
    ".pep": (("Pep8", 1),),
    ".perl": (("Perl", 1),),
    ".pfa": (("PostScript", 2),),
    ".ph": (("Perl", 1),),
    ".php": (("PHP", 1), ("Blade", 2), ("Hack", 1)),
    ".php3": (("PHP", 1),),
    ".php4": (("PHP", 1),),
    ".php5": (("PHP", 1),),
    ".phps": (("PHP", 1),),
    ".phpt": (("PHP", 1),),
    ".phtml": (("HTML+PHP", 2),),
    ".pic": (("Pic", 2),),
    ".pig": (("PigLatin", 1),),
    ".pike": (("Pike", 1),),
    ".pir": (("Parrot Internal Representation", 1),),
    ".pkb": (("PLSQL", 1),),
    ".pkgproj": (("XML", 4),),
    ".pkl": (("Pickle", 4),),
    ".pks": (("PLSQL", 1),),
    ".pl": (("Perl", 1), ("Perl 6", 1), ("Prolog", 1)),
    ".pl6": (("Perl 6", 1),),
    ".plb": (("PLSQL", 1),),
    ".plist": (("XML", 4),),
    ".plot": (("Gnuplot", 1),),
    ".pls": (("PLSQL", 1),),
    ".plsql": (("PLSQL", 1),),
    ".plt": (("Gnuplot", 1),),
    ".pluginspec": (("XML", 4), ("Ruby", 1)),
    ".plx": (("Perl", 1),),
    ".pm": (("Perl", 1), ("XPM", 4), ("Perl 6", 1)),
    ".pm6": (("Perl 6", 1),),
    ".pmod": (("Pike", 1),),
    ".po": (("Gettext Catalog", 3),),
    ".pod": (("Pod", 3),),
    ".podsl": (("Common Lisp", 1),),
    ".podspec": (("Ruby", 1),),
    ".pogo": (("PogoScript", 1),),
    ".pony": (("Pony", 1),),
    ".pot": (("Gettext Catalog", 3),),
    ".pov": (("POV-Ray SDL", 1),),
    ".pp": (("Pascal", 1), ("Puppet", 1)),
    ".pprx": (("REXX", 1),),
    ".prc": (("SQL", 4), ("PLSQL", 1)),
    ".prefab": (("Unity3D Asset", 4),),
    ".prefs": (("INI", 4),),
    ".prg": (("xBase", 1),),
    ".pri": (("QMake", 1),),
    ".pro": (("INI", 4), ("IDL", 1), ("Prolog", 1), ("QMake", 1)),
    ".proj": (("XML", 4),),
    ".prolog": (("Prolog", 1),),
    ".properties": (("INI", 4),),
    ".props": (("XML", 4),),
    ".proto": (("Protocol Buffer", 4),),
    ".prw": (("xBase", 1),),
    ".ps": (("PostScript", 2),),
    ".ps1": (("PowerShell", 1),),
    ".ps1xml": (("XML", 4),),
    ".psc": (("Papyrus", 1),),
    ".psc1": (("XML", 4),),
    ".psd1": (("PowerShell", 1),),
    ".psgi": (("Perl", 1),),
    ".psm1": (("PowerShell", 1),),
    ".pt": (("XML", 4),),
    ".pub": (("Public Key", 4),),
    ".pug": (("Pug", 2),),
    ".purs": (("PureScript", 1),),
    ".pwn": (("PAWN", 1),),
    ".pxd": (("Cython", 1),),
    ".pxi": (("Cython", 1),),
    ".py": (("Python", 1),),
    ".py3": (("Python", 1),),
    ".pyde": (("Python", 1),),
    ".pyi": (("Python", 1),),
    ".pyp": (("Python", 1),),
    ".pyt": (("Python", 1),),
    ".pytb": (("Python traceback", 4),),
    ".pyw": (("Python", 1),),
    ".pyx": (("Cython", 1),),
    ".qbs": (("QML", 1),),
    ".qml": (("QML", 1),),
    ".r": (("R", 1), ("Rebol", 1)),
    ".r2": (("Rebol", 1),),
    ".r3": (("Rebol", 1),),
    ".rabl": (("Ruby", 1),),
    ".rake": (("Ruby", 1),),
    ".raml": (("RAML", 2),),
    ".raw": (("Raw token data", 4),),
    ".rb": (("Ruby", 1),),
    ".rbbas": (("REALbasic", 1),),
    ".rbfrm": (("REALbasic", 1),),
    ".rbmnu": (("REALbasic", 1),),
    ".rbres": (("REALbasic", 1),),
    ".rbtbar": (("REALbasic", 1),),
    ".rbuild": (("Ruby", 1),),
    ".rbuistate": (("REALbasic", 1),),
    ".rbw": (("Ruby", 1),),
    ".rbx": (("Ruby", 1),),
    ".rbxs": (("Lua", 1),),
    ".rd": (("R", 1),),
    ".rdf": (("XML", 4),),
    ".rdoc": (("RDoc", 3),),
    ".re": (("C++", 1), ("Reason", 1)),
    ".reb": (("Rebol", 1),),
    ".rebol": (("Rebol", 1),),
    ".red": (("Red", 1),),
    ".reds": (("Red", 1),),
    ".reek": (("YAML", 4),),
    ".regex": (("Regular Expression", 4),),
    ".regexp": (("Regular Expression", 4),),
    ".rei": (("Reason", 1),),
    ".rest": (("reStructuredText", 3),),
    ".rest.txt": (("reStructuredText", 3),),
    ".resx": (("XML", 4),),
    ".rex": (("REXX", 1),),
    ".rexx": (("REXX", 1),),
    ".rg": (("Rouge", 1),),
    ".rhtml": (("RHTML", 2),),
    ".ring": (("Ring", 1),),
    ".rkt": (("Racket", 1),),
    ".rktd": (("Racket", 1),),
    ".rktl": (("Racket", 1),),
    ".rl": (("Ragel", 1),),
    ".rmd": (("RMarkdown", 3),),
    ".rnh": (("RUNOFF", 2),),
    ".rno": (("Roff", 2), ("RUNOFF", 2)),
    ".robot": (("RobotFramework", 1),),
    ".roff": (("Roff", 2),),
    ".ron": (("Markdown", 3),),
    ".rpy": (("Python", 1), ("Ren'Py", 1)),
    ".rq": (("SPARQL", 4),),
    ".rs": (("RenderScript", 1), ("Rust", 1)),
    ".rs.in": (("Rust", 1),),
    ".rsc": (("Rascal", 1),),
    ".rsh": (("RenderScript", 1),),
    ".rss": (("XML", 4),),
    ".rst": (("reStructuredText", 3),),
    ".rst.txt": (("reStructuredText", 3),),
    ".rsx": (("R", 1),),
    ".ru": (("Ruby", 1),),
    ".ruby": (("Ruby", 1),),
    ".rviz": (("YAML", 4),),
    ".s": (("Unix Assembly", 1),),
    ".sage": (("Sage", 1),),
    ".sagews": (("Sage", 1),),
    ".sas": (("SAS", 1),),
    ".sass": (("Sass", 2),),
    ".sats": (("ATS", 1),),
    ".sbt": (("Scala", 1),),
    ".sc": (("Scala", 1), ("SuperCollider", 1)),
    ".scad": (("OpenSCAD", 1),),
    ".scala": (("Scala", 1),),
    ".scaml": (("Scaml", 2),),
    ".scd": (("SuperCollider", 1),),
    ".sce": (("Scilab", 1),),
    ".sch": (("Eagle", 4), ("XML", 4), ("KiCad Schematic", 4), ("Scheme", 1)),
    ".sci": (("Scilab", 1),),
    ".scm": (("Scheme", 1),),
    ".sco": (("Csound Score", 1),),
    ".scpt": (("AppleScript", 1),),
    ".scrbl": (("Racket", 1),),
    ".scss": (("SCSS", 2),),
    ".scxml": (("XML", 4),),
    ".self": (("Self", 1),),
    ".sexp": (("Common Lisp", 1),),
    ".sfd": (("Spline Font Database", 4),),
    ".sfproj": (("XML", 4),),
    ".sh": (("Shell", 1),),
    ".sh-session": (("ShellSession", 1),),
    ".sh.in": (("Shell", 1),),
    ".shader": (("GLSL", 1), ("ShaderLab", 1)),
    ".shen": (("Shen", 1),),
    ".shproj": (("XML", 4),),
    ".sig": (("Standard ML", 1),),
    ".sj": (("Objective-J", 1),),
    ".sjs": (("JavaScript", 1),),
    ".sl": (("Slash", 1),),
    ".sld": (("Scheme", 1),),
    ".slim": (("Slim", 2),),
    ".sls": (("SaltStack", 1), ("Scheme", 1)),
    ".sma": (("SourcePawn", 1),),
    ".smali": (("Smali", 1),),
    ".sml": (("Standard ML", 1),),
    ".smt": (("SMT", 1),),
    ".smt2": (("SMT", 1),),
    ".soy": (("Closure Templates", 2),),
    ".sp": (("SourcePawn", 1),),
    ".sparql": (("SPARQL", 4),),
    ".spc": (("PLSQL", 1),),
    ".spec": (("RPM Spec", 4), ("Ruby", 1), ("Python", 1)),
    ".spin": (("Propeller Spin", 1),),
    ".sps": (("Scheme", 1),),
    ".sqf": (("SQF", 1),),
    ".sql": (("SQL", 4), ("PLSQL", 1), ("PLpgSQL", 1), ("SQLPL", 1)),
    ".sra": (("PowerBuilder", 1),),
    ".src": (("Erlang", 1),),
    ".srdf": (("XML", 4),),
    ".srt": (("SubRip Text", 4), ("SRecode Template", 2)),
    ".sru": (("PowerBuilder", 1),),
    ".srw": (("PowerBuilder", 1),),
    ".ss": (("Scheme", 1),),
    ".ssjs": (("JavaScript", 1),),
    ".sss": (("SugarSS", 2),),
    ".st": (("HTML", 2), ("Smalltalk", 1)),
    ".stTheme": (("XML", 4),),
    ".stan": (("Stan", 1),),
    ".sthlp": (("Stata", 1),),
    ".ston": (("STON", 4),),
    ".storyboard": (("XML", 4),),
    ".sty": (("TeX", 2),),
    ".styl": (("Stylus", 2),),
    ".sublime-build": (("Sublime Text Config", 4),),
    ".sublime-commands": (("Sublime Text Config", 4),),
    ".sublime-completions": (("Sublime Text Config", 4),),
    ".sublime-keymap": (("Sublime Text Config", 4),),
    ".sublime-macro": (("Sublime Text Config", 4),),
    ".sublime-menu": (("Sublime Text Config", 4),),
    ".sublime-mousemap": (("Sublime Text Config", 4),),
    ".sublime-project": (("Sublime Text Config", 4),),
    ".sublime-settings": (("Sublime Text Config", 4),),
    ".sublime-snippet": (("XML", 4),),
    ".sublime-syntax": (("YAML", 4),),
    ".sublime-theme": (("Sublime Text Config", 4),),
    ".sublime-workspace": (("Sublime Text Config", 4),),
    ".sublime_metrics": (("Sublime Text Config", 4),),
    ".sublime_session": (("Sublime Text Config", 4),),
    ".sv": (("SystemVerilog", 1),),
    ".svg": (("SVG", 0),),
    ".svh": (("SystemVerilog", 1),),
    ".swift": (("Swift", 1),),
    ".syntax": (("YAML", 4),),
    ".t": (("Perl", 1), ("Perl 6", 1), ("Terra", 1), ("Turing", 1)),
    ".tab": (("SQL", 4),),
    ".tac": (("Python", 1),),
    ".targets": (("XML", 4),),
    ".tcc": (("C++", 1),),
    ".tcl": (("Tcl", 1),),
    ".tcsh": (("Tcsh", 1),),
    ".tea": (("Tea", 2),),
    ".tesc": (("GLSL", 1),),
    ".tese": (("GLSL", 1),),
    ".tex": (("TeX", 2),),
    ".textile": (("Textile", 3),),
    ".tf": (("HCL", 1),),
    ".tfstate": (("JSON", 4),),
    ".tfstate.backup": (("JSON", 4),),
    ".tfvars": (("HCL", 1),),
    ".thor": (("Ruby", 1),),
    ".thrift": (("Thrift", 1),),
    ".thy": (("Isabelle", 1),),
    ".tl": (("Type Language", 4),),
    ".tla": (("TLA", 1),),
    ".tm": (("Tcl", 1),),
    ".tmCommand": (("XML", 4),),
    ".tmLanguage": (("XML", 4),),
    ".tmPreferences": (("XML", 4),),
    ".tmSnippet": (("XML", 4),),
    ".tmTheme": (("XML", 4),),
    ".tmac": (("Roff", 2),),
    ".tml": (("XML", 4),),
    ".tmux": (("Shell", 1),),
    ".toc": (("TeX", 2), ("World of Warcraft Addon Data", 4)),
    ".toml": (("TOML", 4),),
    ".tool": (("Shell", 1),),
    ".topojson": (("JSON", 4),),
    ".tpb": (("PLSQL", 1),),
    ".tpl": (("Smarty", 1),),
    ".tpp": (("C++", 1),),
    ".tps": (("PLSQL", 1),),
    ".trg": (("PLSQL", 1),),
    ".ts": (("TypeScript", 1), ("XML", 4)),
    ".tst": (("GAP", 1), ("Scilab", 1)),
    ".tsx": (("TypeScript", 1), ("XML", 4)),
    ".ttl": (("Turtle", 4),),
    ".tu": (("Turing", 1),),
    ".twig": (("Twig", 2),),
    ".txl": (("TXL", 1),),
    ".txt": (("Text", 3), ("reStructuredText", 3), ("TI Program", 1)),
    ".uc": (("UnrealScript", 1),),
    ".udf": (("SQL", 4),),
    ".udo": (("Csound", 1),),
    ".ui": (("XML", 4),),
    ".unity": (("Unity3D Asset", 4),),
    ".uno": (("Uno", 1),),
    ".upc": (("Unified Parallel C", 1),),
    ".ur": (("UrWeb", 1),),
    ".urdf": (("XML", 4),),
    ".urs": (("UrWeb", 1),),
    ".ux": (("XML", 4),),
    ".v": (("Coq", 1), ("Verilog", 1)),
    ".vala": (("Vala", 1),),
    ".vapi": (("Vala", 1),),
    ".vark": (("Gosu", 1),),
    ".vb": (("Visual Basic", 1),),
    ".vba": (("Visual Basic", 1),),
    ".vbhtml": (("Visual Basic", 1),),
    ".vbproj": (("XML", 4),),
    ".vbs": (("Visual Basic", 1),),
    ".vcl": (("VCL", 1),),
    ".vcxproj": (("XML", 4),),
    ".veo": (("Verilog", 1),),
    ".vert": (("GLSL", 1),),
    ".vh": (("SystemVerilog", 1),),
    ".vhd": (("VHDL", 1),),
    ".vhdl": (("VHDL", 1),),
    ".vhf": (("VHDL", 1),),
    ".vhi": (("VHDL", 1),),
    ".vho": (("VHDL", 1),),
    ".vhost": (("ApacheConf", 4), ("Nginx", 4)),
    ".vhs": (("VHDL", 1),),
    ".vht": (("VHDL", 1),),
    ".vhw": (("VHDL", 1),),
    ".view.lkml": (("LookML", 1),),
    ".vim": (("Vim script", 1),),
    ".viw": (("SQL", 4),),
    ".volt": (("Volt", 1),),
    ".vrx": (("GLSL", 1),),
    ".vsh": (("GLSL", 1),),
    ".vshader": (("GLSL", 1),),
    ".vsixmanifest": (("XML", 4),),
    ".vssettings": (("XML", 4),),
    ".vstemplate": (("XML", 4),),
    ".vue": (("Vue", 2),),
    ".vw": (("PLSQL", 1),),
    ".vxml": (("XML", 4),),
    ".w": (("OpenEdge ABL", 1), ("CWeb", 1)),
    ".wast": (("WebAssembly", 1),),
    ".wat": (("WebAssembly", 1),),
    ".watchr": (("Ruby", 1),),
    ".wdl": (("wdl", 1),),
    ".webapp": (("JSON", 4),),
    ".webidl": (("WebIDL", 1),),
    ".webmanifest": (("JSON", 4),),
    ".weechatlog": (("IRC log", 4),),
    ".wiki": (("MediaWiki", 3),),
    ".wisp": (("wisp", 1),),
    ".wixproj": (("XML", 4),),
    ".wl": (("Mathematica", 1),),
    ".wlt": (("Mathematica", 1),),
    ".wlua": (("Lua", 1),),
    ".workbook": (("Markdown", 3),),
    ".wsdl": (("XML", 4),),
    ".wsf": (("XML", 4),),
    ".wsgi": (("Python", 1),),
    ".wxi": (("XML", 4),),
    ".wxl": (("XML", 4),),
    ".wxs": (("XML", 4),),
    ".x": (("Linker Script", 4), ("Logos", 1), ("RPC", 1)),
    ".x10": (("X10", 1),),
    ".x3d": (("XML", 4),),
    ".xacro": (("XML", 4),),
    ".xaml": (("XML", 4),),
    ".xc": (("XC", 1),),
    ".xht": (("HTML", 2),),
    ".xhtml": (("HTML", 2),),
    ".xi": (("Logos", 1),),
    ".xib": (("XML", 4),),
    ".xlf": (("XML", 4),),
    ".xliff": (("XML", 4),),
    ".xm": (("Logos", 1),),
    ".xmi": (("XML", 4),),
    ".xml": (("XML", 4),),
    ".xml.dist": (("XML", 4),),
    ".xojo_code": (("Xojo", 1),),
    ".xojo_menu": (("Xojo", 1),),
    ".xojo_report": (("Xojo", 1),),
    ".xojo_script": (("Xojo", 1),),
    ".xojo_toolbar": (("Xojo", 1),),
    ".xojo_window": (("Xojo", 1),),
    ".xpl": (("XProc", 1),),
    ".xpm": (("XPM", 4),),
    ".xproc": (("XProc", 1),),
    ".xproj": (("XML", 4),),
    ".xpy": (("Python", 1),),
    ".xq": (("XQuery", 1),),
    ".xql": (("XQuery", 1),),
    ".xqm": (("XQuery", 1),),
    ".xquery": (("XQuery", 1),),
    ".xqy": (("XQuery", 1),),
    ".xrl": (("Erlang", 1),),
    ".xs": (("XS", 1),),
    ".xsd": (("XML", 4),),
    ".xsjs": (("JavaScript", 1),),
    ".xsjslib": (("JavaScript", 1),),
    ".xsl": (("XSLT", 1),),
    ".xslt": (("XSLT", 1),),
    ".xsp-config": (("XPages", 4),),
    ".xsp.metadata": (("XPages", 4),),
    ".xspec": (("XML", 4),),
    ".xtend": (("Xtend", 1),),
    ".xul": (("XML", 4),),
    ".y": (("Yacc", 1),),
    ".yacc": (("Yacc", 1),),
    ".yaml": (("YAML", 4),),
    ".yaml-tmlanguage": (("YAML", 4),),
    ".yang": (("YANG", 4),),
    ".yap": (("Prolog", 1),),
    ".yar": (("YARA", 4),),
    ".yara": (("YARA", 4),),
    ".yml": (("YAML", 4),),
    ".yml.mysql": (("YAML", 4),),
    ".yrl": (("Erlang", 1),),
    ".yy": (("Yacc", 1),),
    ".zcml": (("XML", 4),),
    ".zep": (("Zephir", 1),),
    ".zimpl": (("Zimpl", 1),),
    ".zmpl": (("Zimpl", 1),),
    ".zone": (("DNS Zone", 4),),
    ".zpl": (("Zimpl", 1),),
    ".zsh": (("Shell", 1),),
}
